version: '3.9'

services:
  gateway:
    build:
      context: ./Email.Services/Email.Services.Gateway
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network

  api:
    build:
      context: ./Email.Services
      dockerfile: Email.Services.API/Dockerfile
    ports:
      - "8081:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-api,1433;Database=Services_EmailAPI;User Id=sa;Password=SG@Admin123;Encrypt=False;TrustServerCertificate=True
    networks:
      - app-network

  processor:
    build:
      context: ./Email.Services
      dockerfile: Email.Services.Processor/Dockerfile
    ports:
    - "8082:80"
    depends_on:
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-processor,1433;Database=Services_EmailLogs;User Id=sa;Password=SG@Admin123;Encrypt=False;TrustServerCertificate=True
    networks:
      - app-network

  ui:
    build:
      context: ./email.ui
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  sql-api:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    container_name: sql-api
    hostname: sql-api
    ports:
      - "1500:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SG@Admin123"
      MSSQL_PID: "Evaluation"
      MSSQL_TLS_VERSION: "1.2"
      restart: unless-stopped
    networks:
      - app-network

  sql-processor:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    container_name: sql-processor
    hostname: sql-processor
    ports:
      - "1501:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SG@Admin123"
      MSSQL_PID: "Evaluation"
      MSSQL_TLS_VERSION: "1.2"
      restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge